### ISSUE TITLE
Lesson does not include in-browser IDE

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/cli-essentials-bash-files-and-directories#5]
This lesson lacks the in-browser IDE, which leaves novices without an opportunity to practice these commands and leaves the door open for confusion. For instance, I worked with one student who was entering these commands into a DOS prompt on Windows and didn't understand why it wasn't working.

**Comment by sgharms** [comment]
@ivalentine We don't have the ability to turn on the IDE without adding a test to trigger it. I'll add this as a feature request though!
